apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    infra.local/database: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cassandra
  labels:
    infra.local/database: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: qdrant
  labels:
    infra.local/database: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: workloads
  labels:
    infra.local/database-client: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    infra.local/monitoring: "true"