{
 "title": "Commerce API RED",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(service) (rate(api_requests_total[2m]))",
     "legendFormat": "{{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "5xx / second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(service) (rate(api_requests_total{status=~\"5..\"}[2m]))",
     "legendFormat": "{{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "p95 seconds",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(service, le) (rate(api_request_duration_seconds_bucket[2m])))",
     "legendFormat": "{{service}} {{instance}}"
    }
   ]
  },
  {
   "title": "Collector scrape availability",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "up{job=\"otel\"}",
     "legendFormat": "OpenTelemetry Collector"
    }
   ]
  }
 ]
}