apiVersion: v1
kind: Secret
metadata:
  name: citus-credentials
  labels:
    app.kubernetes.io/part-of: citus
type: Opaque
stringData:
  password: {{ required "postgres.password must be provided through Terraform" .Values.postgres.password | quote }}
  pgpass: {{ printf "*:*:*:postgres:%s" .Values.postgres.password | quote }}