apiVersion: v1
kind: Service
metadata:
  name: citus-coordinator
  labels:
    app.kubernetes.io/name: citus-coordinator
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: citus-coordinator
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  labels:
    app.kubernetes.io/name: citus-worker
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: citus-worker
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP