rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender
appender.console.name = ConsoleAppender
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = {"timestamp":"%d{ISO8601}","severity":"%p","logger":"%c","message":"%enc{%m}{JSON}","exception":"%enc{%ex}{JSON}"}%n
logger.akka.name = akka
logger.akka.level = WARN
logger.netty.name = org.jboss.netty
logger.netty.level = WARN
